id: I669B259C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T07:59:17+00:00'
last_modified: '2022-06-07T21:59:54.659929+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1113
  title: བྱང་ཆུབ་སེམས་པའི་རྟོགས་པ་བརྗོད་པ་དཔག་བསམ་འཁྲི་ཤིང་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    1E27:
      image_group_id: I1CZ1388
      title: ''
      total_pages: 10
      order: 1
      base_file: 1E27.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
